[supervisord]
nodaemon=true
user=dk400
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:robot]
command=celery -A dk400.robot.worker worker --beat --loglevel=info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:api]
command=uvicorn dk400.api.main:app --host 0.0.0.0 --port 8400
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:web]
command=uvicorn dk400.web.server:app --host 0.0.0.0 --port 8500
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
